name: view-github-object
on: [push]

jobs:
  view-github-object:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: GITHUB CONTEXT
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: get commit message
        run: |
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: show commit message
        run: echo $commitmsg

      - name: step1
        if: contains( env.commitmsg , 'try' )
        run: echo hello
